const express = require("express");
const router = express.Router();
const homeController = require("../controllers/home.controller");
const userController = require("../controllers/user.controller");
const courseController = require("../controllers/course.controller");
const authController = require("../controllers/auth.controller");
router.get("/", homeController.index);
router.get("/users", userController.index);
router.get("/users/:id", userController.getDetail);
router.post("/users", userController.create);
router.post("/users/:id", userController.update);
router.post("/users/:id/delete", userController.delete);
router.get("/courses", courseController.index);
router.get("/courses/:id", courseController.find);
router.post("/courses", courseController.create);
router.post("/courses/:id", courseController.update);
router.delete("/courses/ids", courseController.deleteIds);
router.delete("/courses/:id", courseController.delete);
router.get("/login", authController.loginForm);
router.post("/login", authController.login);
router.post("/logout", authController.logout);
module.exports = router;
