data = {
	geo: {},
	ip: undefined,
	nextUrl: {
		href: "http://localhost:3000/san-pham",
		origin: "http://localhost:3000",
		protocol: "http:",
		username: "",
		password: "",
		host: "localhost:3000",
		hostname: "localhost",
		port: "3000",
		pathname: "/san-pham",
		search: "",
		hash: "",
	},
	url: "http://localhost:3000/san-pham",
	bodyUsed: false,
	cache: "default",
	credentials: "same-origin",
	destination: "",
	headers: {
		accept: "*/*",
		"accept-encoding": "gzip, deflate, br, zstd",
		"accept-language": "en-US,en;q=0.9,vi;q=0.8",
		connection: "keep-alive",
		dnt: "1",
		host: "localhost:3000",
		"next-url": "/",
		referer: "http://localhost:3000/",
		"sec-ch-ua":
			'"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
		"sec-ch-ua-mobile": "?0",
		"sec-ch-ua-platform": '"Windows"',
		"sec-fetch-dest": "empty",
		"sec-fetch-mode": "cors",
		"sec-fetch-site": "same-origin",
		"user-agent":
			"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
		"x-forwarded-for": "::1",
		"x-forwarded-host": "localhost:3000",
		"x-forwarded-port": "3000",
		"x-forwarded-proto": "http",
	},
	integrity: "",
	keepalive: false,
	method: "GET",
	mode: "cors",
	redirect: "follow",
	referrer: "about:client",
	referrerPolicy: "",
};