import Header from "./components/Header/Header";
import { Nunito } from "next/font/google";
import "./globals.scss";
import Providers from "@/redux/Providers";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { cookies } from "next/headers";
import SessionProviders from "@/session/SessionProviders";
import { getServerSession } from "next-auth";
config.autoAddCss = false;
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const nunito = Nunito({ subsets: ["latin"], display: "swap", weight: ["400", "200", "300", "700"] });
const getPageData = async () => {
    const response = await fetch(process.env.NEXT_PUBLIC_URL + "/pages");
    const data = await response.json();
    return data;
};

export default async function RootLayout({ children }) {
    const data = await getPageData();
    const dataCookies = cookies();
    const theme = dataCookies.get("theme");
    return (
        <html lang="en">
            <body className={`${nunito.className} ${theme?.value === "dark" ? "dark" : "light"}`}>
                <Providers>
                    <Header data={data} />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
