import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata = {
  title: 'F8 học lập trình để đi làm!',
  description: 'Generated by create next app',
  keywords: "f8, fullstack, html, css",
  openGraph: {
      title: "tiêu đề hiển thị trên FB",
      images: [
          {
              url: "https://f8-fullstack.vercel.app/assets/images/f8-fullstack.png",
              width: 800,
              height: 600
          }
      ]
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
