import DetectNetWork from "./posts/DetectNetwork";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				{children}
				<DetectNetWork />
			</body>
		</html>
	);
}
